### ISSUE TITLE
Erro ao visualizar O.S após implementar assinatura.

### ISSUE THREAD

**Issue by naodoubuff** [juliolobo/Assinatura-MapOS-4.42.0#21]
Utilizando XAMPP PHP 8.2 instalação limpa.
Após testar assinatura, apresenta erro ao visualizar O.S
![image](https://github.com/juliolobo/Assinatura-MapOS-4.42.0/assets/78187809/10892184-0b47-4961-bf43-1435b68cad75)

**Comment by naodoubuff** [comment]
Corrigi atualizando o banco de dados e atualizando o sistema  4.42. A versão do site não era a ultima, e sim a do git.

**Comment by juliolobo** [comment]
Exato, houveram atualizações no Github. Sempre usa a versão do Github. Parabéns por encontrar a solução do problema!
