### ISSUE TITLE
erro no assinaatura

### ISSUE THREAD

**Issue by fabianoandersons** [juliolobo/Assinatura-MapOS-4.42.0#22]
boa tarde julio, comecei fazer a assinatura no meu mapos e parei na mesma parte rsrr, nao consegui fazer gravar no banco, voce conseguiu avanacar nessa parte?

**Comment by juliolobo** [comment]
Precisa adicionar uma exceção no csrf no config.php pois houveram modificação de segurança no Mapos.
Em breve atualizarei a assinatura para funcionar de forma correta

**Comment by fabianoandersons** [comment]
coloquei a excessao e funfou! valew man
