### ISSUE TITLE
Assinatura nao aparece apos salvar

### ISSUE THREAD

**Issue by fabianoandersons** [juliolobo/Assinatura-MapOS-4.42.0#23]
Bom dia julio, estou fiz os ajustes e funcinou legal a assinatura, so que nao recupera do banco a imagem, no momento que feita ela fica aparente mais dando um reload na OS ela ja aparece com icone de imagem. manja o que pode ser?\

**Comment by fabianoandersons** [comment]
<img width="198" alt="Captura de Tela 2024-07-03 às 09 59 40" src="https://github.com/juliolobo/Assinatura-MapOS-4.42.0/assets/124322418/e3fe858b-5a43-4596-9408-31638a6d007f">

**Comment by juliolobo** [comment]
Mande um print de como tá salvando no banco de dados

**Comment by fabianoandersons** [comment]
![Captura de Tela 2024-07-04 às 10 50 13](https://github.com/juliolobo/Assinatura-MapOS-4.42.0/assets/124322418/a40a9eea-f0d3-4892-b384-d6a2a53df948)
essa primeira eu editei e tire o [removed]

**Comment by fabianoandersons** [comment]
um ponto relevante é que meu mapos esta hospedado na hostgator, nao sei se poder ser algo relacionado a bloqueio

**Comment by fabianoandersons** [comment]
consegui resolver mudando essa tag no .env, GLOBAL_XSS_FILTERING=false porem nao acho seguro, tem alguma ideia?
